### ISSUE TITLE
POST /resource should provide an error if they try to provide an ID.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#105]

**Comment by jcoyne** [comment]
Currently the Repository schema has an id on it.  This shows up in the docs as what you should provide to the create resource method.   Perhaps we need to split the request schema from the response schema?

**Comment by cmh2166** [comment]
yeah. I was hoping we could avoid this, but this seems to be a real need to split that.

**Comment by jcoyne** [comment]
I created #193 regarding splitting the parameter model.

**Comment by cmh2166** [comment]
@jcoyne splitting will not work (i already tried), since it requires the ability to say "you cannot provide this specific field", which the subset of json schema used in swagger and implemented via go-swagger.

**Comment by jcoyne** [comment]
@cmh2166 yes, lets take a look at this together.

**Comment by cmh2166** [comment]
Now wrapped up in #292
