### ISSUE TITLE
Fedora 4 API comparison to TACO

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#126]
Tom request for Christina

**Comment by jcoyne** [comment]
I think this is true of the API regardless of what implementation
1. Can't handle ordered lists (which can be worked around, but hurts performance)

And this is true of all implementations that I know of (maybe not A Colburn's?): 
1. Centralized vs. Distributed (which goes to performance and scale requirements)

**Comment by cmh2166** [comment]
Scheduled meeting for this. Need to make prep materials and confirm Tom will actually show up.

**Comment by cmh2166** [comment]
Invite Stu.
