### ISSUE TITLE
AWS Costs Comparisons & Notes

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#14]
- costs / analytics & monitoring in AWS
- costs for running a current VM for comparison (hyku locally? argo?)
- ideally including an estimate of staff time per month/year to patch, run maintenance, etc.
- costs for running serverless in AWS
- AWS cost calculator
- NYPL info?
- Fedora serverless implementations (trellis, lambdora)?
- costs for running containers in AWS
- AWS cost calculator

**Comment by cmh2166** [comment]
See comment from @aaron-collier on #3

**Comment by jcoyne** [comment]
AWS Cost page for S3: https://aws.amazon.com/s3/pricing/

Estimate:  Storage costs + request costs + transfer costs = total
Ben says we use 12tb for scratch space on SDR2. This is available space, not utialized space, so it should serve as a good upper bound for us.
  Storage: est 12,000GB (12TB) * $0.023 /gb = $276/mo

Request cost:  TBD

Transfer cost: TBD

**Comment by cmh2166** [comment]
This issue was moved to sul-dlss/sdr3-planning#37
