### ISSUE TITLE
Policy: confirm identifier schema for SDR & TACO

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#140]
Can the policy team confirm this is the identifier schema wanted? https://github.com/sul-dlss-labs/taco/wiki/Identifier-schema
(Note, if so, we will be required to have internal identifiers that vary within TACO from what we present out in the world given versioning considerations & filename presence / changes over time issues).

**Comment by blalbrit** [comment]
Confirmed for SDR schema from my point of view.

**Comment by hannahfrost** [comment]
Confirmed for me too. I like it not only is it logical, but because it also is consistent with the convention often used for Source IDs. A nice parallel.

**Comment by hannahfrost** [comment]
We added notes to the above link based on the outcomes of our discussion

**Comment by cmh2166** [comment]
Thanks! Closing.
