### ISSUE TITLE
get note on readme that localstack test python requirements

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#148]

**Comment by cmh2166** [comment]
localstack or awscli (perhaps latter not used in circleci) seems to require python 2.7. confirm/deny + document.

**Comment by jcoyne** [comment]
I think it's just `awslocal` that was giving you trouble.  We could rewrite this using just aws-cli if that's better.

**Comment by jcoyne** [comment]
localstack also seems to have a Java dependency too.

**Comment by jcoyne** [comment]
localstack supports both Python 2 + 3 and has a dependency on Java 8: https://github.com/localstack/localstack#requirements
