### ISSUE TITLE
Proposal: rename operationIds

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#155]
`depositNewFile` -> `depositFile`
`depositNewResource` -> `depositResource`

Two reasons:
1. It would make the generated code easier to understand. Presently we have structs like: `NewDepositNewResourceCreated`. `NewDepositResourceCreated` would be easier to understand.
2. Consistency with other operations which are `updateResource` not `updateExistingResource`

**Comment by cmh2166** [comment]
Yeah, I agree with this.
