### ISSUE TITLE
Proposal: Rename body to payload for update in spec

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#156]
The body is named `payload` in the create resource path: https://github.com/sul-dlss-labs/taco/blob/master/swagger.json#L25 but `body` in the update https://github.com/sul-dlss-labs/taco/blob/master/swagger.json#L99

Would it be possible to rename the update to `payload` for consistency? I'm trying to consolidate a bit of code that needs to be duplicated between `create` and `update` and following the same naming convention would help minimize repeating code.

**Comment by cmh2166** [comment]
sure.
