### ISSUE TITLE
Create Account & Set Up for Circle-CI

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#16]
For Go, Docker, AWS continuous deployment.

@eefahy can you include a few lines of docs somewhere on why Circle CI (as it is a new selection, to include with our repo + selection docs)?

**Comment by cmh2166** [comment]
@eefahy done?

**Comment by cmh2166** [comment]
issues with docker build + code practices blocked this. moving to next until ready to reapproach (blocked currently by #61

**Comment by cmh2166** [comment]
Linked to #63

**Comment by aaron-collier** [comment]
@eefahy and @cmh2166 Thinking we can close this now?
