### ISSUE TITLE
A client should be able to associate a file with an object

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#162]
Define what the users need here?  Do they just update with "<resource> <contains> <fileResource>"

Then when they retrieve is the "<resource> <contains> " returning a list of TACO URIs? Or is it DRUIDS?

Would a client want to do something like `/v1/resource/999999?include=files`?

**Comment by cmh2166** [comment]
Per our group work + the analysis ticket + recent policy group work discussed, clients can do 1 of 2 things:

1. create an resource of type file (https://github.com/sul-dlss-labs/taco/wiki/Prototype-Processing-Framework#post-resource-with-payload--json-ld-representation-of-a-file-typeurifile) that provides a retrievable file (binary) pointer
2. upload a binary, that generates a resource of type file, and then then patch the file resource with metadata that can't be provided via the binary alone + processing kicks off there.

**Comment by cmh2166** [comment]
we do not want to do 'include=files' - that has not been approved in any of the group work we've done.

**Comment by cmh2166** [comment]
closing this otherwise to break into clarify existing work tickets + a separate identifier schema question.
