### ISSUE TITLE
What should happen if we write to dynamodb and can't connect to kinesis

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#166]
Should we try to undo the dynamodb insert, or just log an error?

**Comment by cmh2166** [comment]
Group discussion of feb. 26:
- leave record in dynamodb with provided data as is
- log error of connection to kinesis
- write better error handling for retries or flagging records that weren't able to be processed
- make sure provenance / resource state is clear to know that the resource as received but not processed (make this a simple lifecycle state in MAP for now?)

**Comment by cmh2166** [comment]
@aaron-collier @eefahy look right?

**Comment by eefahy** [comment]
LGTM

**Comment by aaron-collier** [comment]
Doc'd here: https://github.com/sul-dlss-labs/taco/wiki/Prototype-Processing-Framework#error-recovery-framework
