### ISSUE TITLE
Do we want a version 0?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#183]
If the  user didn't provide a version, should we automatically add version: 0? This makes it easier for us to do a look up on the object with DRUID: X that has the higest version number.

This would support the requirement of being able to lookup a resource with an previous version number.

**Comment by cmh2166** [comment]
we should automatically assign a version to all created resources, though i thought the work / specs so far said to start at 1.

**Comment by aaron-collier** [comment]
@jcoyne do you see some reason that version: 0 works any differently than version: 1 as the initial version?

**Comment by jcoyne** [comment]
Does this imply that we should validate that a version MUST be in a create resource request? Or should we automatically add `version: 1` to the resource we create?

**Comment by cmh2166** [comment]
We automatically add a version on create. 0 might not be a bad idea; allows people to add 1 upon a release update.

**Comment by cmh2166** [comment]
Versioning is queued up for next Thursday's policy meeting.
