### ISSUE TITLE
Dockerize rails-suri?

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#189]
- [x] Review rails-suri code base
- [ ] Review existing docker files created by chris
- [ ] Create docker file to deploy rails-suri
- [ ] Should we go-ify the above?

**Comment by cmh2166** [comment]
See #175

**Comment by cmh2166** [comment]
Per @eefahy's review, this is another fake out service.

To be discussed here, what extent do we want to stub something.

**Comment by cmh2166** [comment]
@eefahy should close if agrees.

**Comment by jcoyne** [comment]
@eefahy I took a look at this today, and discussed with Chris.  As far as I have been able to find, this is functionally equivalent to the Java SURI service (at least for the parts we actually use).  I think we should consider perusing this and I'd love to discuss more with you at code4lib.  Maybe we can spin this off to a separate infrastructure subproject just to rid ourselves of the Java/Oracle SURI.

**Comment by cmh2166** [comment]
@jcoyne this doesn't seem to lessen the devOps burden on @eefahy for what is not an immediate goal for this particular project. I remember us agreeing to just having a fake out service internal to TACO for the time being, and that still seems sufficient instead of throwing up another project.
