### ISSUE TITLE
UpdateResource handler Steps

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#190]
- [x] Well formed JSON? (syntactic only)
- [x] Permissions check? (call to Permissions service, to be stubbed out)
- [ ] Check ("validate") that required fields for processing present:
   - [x] validate @context
   - [x] validate @type is URI for type we can handle
   - [x] @id
   - [x] label (string)
   - [x] access (string): [‘world’, ‘stanford’, ‘location-based’, ‘citation-only’, ‘dark’]
   - [x] preserve (boolean)
   - [x] publish (boolean)
   - [x] Check structural metadata.
   - [ ] Deduplication of resources: Validate sourceid is unique within TACO if provided
- [x] Retrieve the existing resource metadata from DynamoDB.
- [x] Merge that existing metadata with provided new metadata from DynamoDB (including overwrites).
- [x] Persist the updated resource metadata with that DRUID.
- [x] Return the DRUID to the Client / User who made the request.
- [x] Message to TACO Processing for asynchronous resource processing:

**Comment by cmh2166** [comment]
@aaron-collier does this help with checking off what is required of updateResource handler code in TACO?

**Comment by aaron-collier** [comment]
Yup, thanks!

**Comment by cmh2166** [comment]
Things not complete have individual tickets. Closing this.
