### ISSUE TITLE
Persistence Layer Selection Criteria & Options

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#2]
What are the criteria (among the tech team) for selecting our TACO persistence layer(s)? What are some options we should consider? 

To be done also, linking any requirements that explicitly map to persistence layer (not API or wrapper code) selection criteria.

Just opening for a discussion point leading to our working sessions next week.

**Comment by cmh2166** [comment]
Need to put criteria + selection notes in repo wiki, then open new ticket for link to user stories.

**Comment by aaron-collier** [comment]
@cmh2166 are we comfortable closing this now that the wiki page has been established?
