### ISSUE TITLE
Update handler should use UpdateItem

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#204]
Currently it does a full replace using dynamodb "PutItem", but maybe we want to do "UpdateItem"

Otherwise we ought to change the swagger to use the PUT action rather than the PATCH action.

Ref #47

**Comment by cmh2166** [comment]
Connected to #229

**Comment by aaron-collier** [comment]
Closing in favor of overwriting item to avoid duplicate complexity of update statements.

**Comment by jcoyne** [comment]
Aaron, should we switch back to PUT then?

**Comment by cmh2166** [comment]
Not in my opinion, since were not moving the resource to a new identifier. The merging still occurs, just not in the database directly.
