### ISSUE TITLE
Add what is needed to reintegrate Filesets model in existing work

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#211]
See #139

**Comment by jcoyne** [comment]
I wonder if we want to do:
1. Create an object resource:`POST /resources`
2 Attach a file: `POST /file?object_id=XXXX` (id from step 1)

then step 2 can create the FileSet node as well as the File node.

If we need to attach a second file to a particular fileset we could do 
` POST /file?file_set_id=XXXX`


OR

we could do
1. Create an object `POST /resources`
2. Create a FileSet `POST /resources`
3. Create a File `POST /file?file_set_id=XXXX`
4. Create a second File `POST /file?file_set_id=XXXX`


This later way is a lot more chatty, but might be simpler for a prototype.

**Comment by cmh2166** [comment]
I don't prefer the first approach because it is too implicit, imo. 

The second approach is what the group decided last time we talked about this, iirc.

**Comment by cmh2166** [comment]
i don't think Filesets change what we've mapped out as a group at that level. But ordering might. And retrieval of children concerns might. And identifiers / versioning / transform to PURL or MOAB might.

**Comment by aaron-collier** [comment]
I think option 2 provides us with the most clarity for code structure, where the implicitness of the first option seems to both complicate the code and testing.
