### ISSUE TITLE
Identifier <=> Internal Identifier Schema

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#212]
What mappings are needed in TACO to handle the requested identifier schema from stakeholders / policy (seen here:  https://github.com/sul-dlss-labs/taco/wiki/Identifier-schema) and what we need to manage internally to TACO?

**Comment by cmh2166** [comment]
@aaron-collier @jcoyne @eefahy please confirm this matches expectations: https://github.com/sul-dlss-labs/taco/wiki/Identifier-schema

**Comment by aaron-collier** [comment]
👍

**Comment by eefahy** [comment]
👍
