### ISSUE TITLE
Should files go in a separate table than resources

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#214]
I think they should because they have different properties (e.g. `file_uri`, `original_filename`, `checksum`, etc)  This is also an easy way to partition file metadata from structural metadata and it makes some type checking unnecessary.

**Comment by cmh2166** [comment]
"file metadata" versus "structural metadata" is not an important distinction for our modeling so far.

If we are separating by MAP, then there should be a different table for each resource type we have: Collection, Objects, Filesets, Files.

**Comment by cmh2166** [comment]
(the last part of that being what I thought we had already discussed as a group)
