### ISSUE TITLE
if focusing on inverse membership relationships (i.e. is_member_of), how / where to handle ordering per MAP?

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#220]
Had been looking at IIIF Ordering modeling[1] to copy. However, where is this generated? Provided? asserted? 

http://iiif.io/model/shared-canvas/1.0/#OrderingIntro

**Comment by cmh2166** [comment]
Thinking at higher level API / assembly section:

It will know collection & object, or object & part objects, so it can indicate:

(for collections + objects):
1. create collection + provide order of to be made objects (through... UUIDs of objects? something else?)
2. create object + assert `is_member_of` collection
3. resolve collection's ordering of objects to object URIs.

(for objects + objects)
1. create parent object (we're keeping object oriented so far)
2. create part object + assert `is_member_of` parent object
3. assert on parent object... order of children objects? 

Alternatively, make ordering resources separate resources and connect to parent?

**Comment by cmh2166** [comment]
Another option is to have `next` / `previous` asserted on the Objects, once Object identifiers are known that is resolved.

**Comment by jcoyne** [comment]
What if we don't use `is_member_of` for now, and focus just on `has_members`, then we are able to assert membership and order in one statement.  Is there something we need that make that approach unfeasible? This is the approach Valkyrie uses and it seems to work out well there.

**Comment by cmh2166** [comment]
because that, again, changes how we're handling processing expectations at a high level.

**Comment by cmh2166** [comment]
it returns to something we've discussed a few times. we can't switch structure each time some reason for the inverse comes up, alas.

**Comment by jcoyne** [comment]
@cmh2166 then we should figure out what happens when we have objects A, B, C, D

Then I say:

`A` has these children in order `has_members` `B, C`.

Then I say `D` `is_member_of` `A`

And finally when I query "What are the members of `A`?" What should be the response?  Should `has_members` have any implied order?

**Comment by cmh2166** [comment]
that's what I'm working on right now. :-)

**Comment by cmh2166** [comment]
and querying is out of scope currently, but what you proposed is exactly why you said you preferred inverse membership direction last time we talked about this in person, iirc (bc of collection querying object for type validation load).

**Comment by jcoyne** [comment]
Okay, `next / previous` is also hairy as you can have two actors writing simultaneously and making differing assertions about what thing is `next`.   In Hyrax we encountered this and had to create a global mutex to make certain that only one actor was operating on that at a time.  

When I said querying, what I meant, was when I do a get request for an object (which is in scope).  Presumably it would return it's relationship assertions, right?
