### ISSUE TITLE
Go Framework?

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#23]
Review options (including option of not using a web framework with Go):

- Beego: 
  - https://github.com/astaxie/beego
  - https://beego.me
- Buffalo: 
  - https://github.com/gobuffalo/buffalo
  - https://gobuffalo.io
- Echo: 
  - https://github.com/labstack/echo
  - https://echo.labstack.com
- Gin:
  - https://github.com/gin-gonic/gin
  - https://gin-gonic.github.io/gin
- Iris: 
  - https://github.com/kataras/iris
  - https://iris-go.com
- Revel: 
  - https://github.com/revel/revel
  - https://revel.github.io

**Comment by jcoyne** [comment]
Gin is looking good...we'll start there.

**Comment by cmh2166** [comment]
@jcoyne can you share your reasons why for this so we can have a record of that?

**Comment by cmh2166** [comment]
See another opinion on Gin: https://nordicapis.com/7-frameworks-to-build-a-rest-api-in-go/

**Comment by cmh2166** [comment]
Ends up we are not using a framework due to the Swagger Generator selection. Documenting and closing this issue.
