### ISSUE TITLE
Rename fieldname "preserve" to a non-reserved word in Dynamodb?

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#242]
I'm getting the following error when updating the preserve field:

```
2018/02/23 13:32:07 ValidationException: Invalid UpdateExpression: Attribute name is a reserved keyword; reserved keyword: Preserve
	status code: 400, request id: 1ef67d15-2ed3-4afb-9292-7546f53058a2
```

This is also noted in:

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html

Perhaps we should rename this to `sdr_preserve` or something similar?

**Comment by cmh2166** [comment]
sure, we can do that. i can merge that into the maps update pr i'm trying to get through now with a few diff changes, if that works

**Comment by cmh2166** [comment]
also applies to UUID. fixing.
