### ISSUE TITLE
Integrate JSON MAP into TACO

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#250]
- [ ] Get Swagger spec to call JSON MAP
- [ ] Update handlers / abstractions
- [ ] Update dynamodb setup / schema
- [ ] Possible changes to TACO validation of metadata & structural validation

**Comment by jcoyne** [comment]
I think this means, update swagger.json to make the schema ref the external documents in the `map/` directory.  But if that is the case, which MAP?  I would think we'd want it to support Collection/Fileset/DRO, but Swagger 2.0 does not support `oneOf`.  Am I off base here?

**Comment by cmh2166** [comment]
Related to #105
