### ISSUE TITLE
How do we authorize create within a context?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#257]
Assuming we want to create a resource within a collection, we have said there should be an authorization check "Can user X create a new resource Y in collection Z". However, due to how we track collection membership (in the MAP), we first have to create the resource Y, and then add it to collection Z as a second step.  At what point should the authorization be checked?

**Comment by cmh2166** [comment]
This is probably going to happen at the Administration level, not TACO, given the constraints of contextual permissions at the Collection or Repository (or Object, if complex) level.

**Comment by cmh2166** [comment]
Let's open an Administration repo to start moving these tickets to, I think.

**Comment by cmh2166** [comment]
This issue was moved to sul-dlss-labs/cocinero#2
