### ISSUE TITLE
Support PATCH with delete parameter

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#259]
See #48 

"Delete" (as understood at the higher level administration level marks a record and provides a gravestone message) - Will:

* Calls PATCH /resource/{id}
* Payload: delete: true, gravestronemsg: string, access: false, publish: false
* Permissions updated - To Be Defined
* Message to processing

Questions:
Regarding `access: false`. Currently access is a string that is constrained to be an enumeration.  Should we change that constraint, or should we change this requirement to be something like `access: "dark"`?

Should we say:
> `PATCH /resource/{id}` with `delete: true` must be used in conjunction with gravestonemsg and access: "dark", publish: false ?

**Comment by cmh2166** [comment]
Delete is already in the metadata schema. This is not needed.

**Comment by cmh2166** [comment]
Any other questions on this? Beyond catching `access: false` that just appeared from a whiteboard write up?

**Comment by jcoyne** [comment]
Just that we should write an integration test for this operation and see what comes up.

**Comment by cmh2166** [comment]
Move to administration & confirm that is correct place to handle this logic.
