### ISSUE TITLE
All items should use UUID as primary keys (not druids)

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#266]
- [ ] identification.identifer should hold a DRUID for Collections & DRO. For Fileset & File, copy the UUID there for now.
- [ ] Add `identification.identifer` secondary index with a sort field of `version`
- [ ] Add `identification.identifer` secondary index with a sort field of `currentVersion`

Note that we can't persist `identification.identifier` as a nested document:
> Every attribute in the index key schema must be a top-level attribute of type String, Number, or Binary. Other data types, including documents and sets, are not allowed.
 
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SecondaryIndexes.html

**Comment by cmh2166** [comment]
interesting. will also rework in MAPs.

**Comment by jcoyne** [comment]
@cmh2166 Does the MAP be an exact reflection of how we persist to DynamoDb, or can we have a mapping between our persistence data and our API data?

**Comment by cmh2166** [comment]
There’s no need for it to bifurcate at this point, and I’d been looking at I’d as something to move to top level regardless.

**Comment by aaron-collier** [comment]
Related to #408, missing `identification.identifier` is blocking round trip of data for update.
