### ISSUE TITLE
Add delete route to /file in swagger.json

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#270]
Add the http DELETE method to the swagger.json specification for the /file path.

Refs #260

**Comment by jcoyne** [comment]
I'm not sure we need this. Can we talk about it?

**Comment by cmh2166** [comment]
We do not need it.

To delete a File (binary), per discussion & spec, you issue a DELETE request to /resources for the File (metadata) and that triggers workflow that deletes the BINARY in S3.

**Comment by aaron-collier** [comment]
Cool. I was just going through the swagger, and thought we may have missed. it. Thanks for the clarification, closing. :-)
