### ISSUE TITLE
Meaning of {ID} in /resource/{ID} routes

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#271]
Is that `identification.identifier` or `identification.sdrUUID`, or both?

Depending on what we choose we may need to write tickets to update the handlers.

**Comment by cmh2166** [comment]
identification.identifier.

**Comment by jcoyne** [comment]
In that case we need to wright a ticket that says the Update/Get should return the one that matches the identifier and also has `currentVersion: true`. Delete should delete all the versions?

**Comment by cmh2166** [comment]
I can expand the existing write up with this if needed.

**Comment by jcoyne** [comment]
Do we need a route that will allow us to retrieve an older version of a resource?

**Comment by cmh2166** [comment]
Per previous discussions, that will be added to the GET route as a version flag. Not yet written out.

**Comment by cmh2166** [comment]
I think we already have answered the original question though. Use `identification.identifier`.
