### ISSUE TITLE
Create file generate file resource from scheme

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#280]
Can we generate / set defaults from the schema

**Comment by jcoyne** [comment]
I believe we could do this. @cmh2166 can you suggest some defaults for us to put in `maps/DepositFile.json`?

**Comment by cmh2166** [comment]
related to #379

**Comment by cmh2166** [comment]
See the defaults added to the MAP. this doesn't cover all required fields, but the ones in which we can make a default: https://github.com/sul-dlss-labs/taco/blob/file-defaults/maps/DepositFile.json
