### ISSUE TITLE
separate unit tests from integration/end-to-end tests

### ISSUE THREAD

**Issue by eefahy** [sul-dlss-labs/taco#288]
unit tests and e2e tests need different environments to run so we should be able to run them specifically in different environments. For example, once the tests have been separated, a possible workflow for testing could be to have ci test the unit tests on the copied code within the ci container and then run the e2e tests on the containers built via docker compose.

**Comment by jcoyne** [comment]
@eefahy Do you have any ideas of how this should be done?

Presently you can separate them by doing:

Unit tests:
```
go test -v ./... -short
```

Integration:
```
go test -v ./test
```

do you know of a better pattern?

**Comment by eefahy** [comment]
Your comment is not currently accurate as `repository_test.go` would never be run in that case. I like the separation of the integration tests in its own directory but perhaps it would be better to do something like the third suggestion here: https://www.philosophicalhacker.com/post/integration-tests-in-go/

**Comment by eefahy** [comment]
Yeah, I think it makes sense to be honest. It would be cool to be able to test each package in isolation as that leverages the purpose of having a package in the first place.

**Comment by jcoyne** [comment]
@eefahy what I mean by that is, we'd have to give up using `go test -v ./...`. We're cool with that?

**Comment by aaron-collier** [comment]
@eefahy I think, based on pairing with @jcoyne  this morning, that we're able to isolate package testing, but without using flags. Perhaps this isn't exactly what you are hoping for in the first comment for docker, maybe we can pair/walk through this a bit together soon?

**Comment by eefahy** [comment]
I'd love to hear what you've come up, absolutely. I look forward to documentation and pairing/reviewing  and am happy to describe what the CI implications are.

**Comment by eefahy** [comment]
This is related to how we run tests in a future `Makefile`

**Comment by eefahy** [comment]
Existing questions mocking ext services for unit tests

**Comment by aaron-collier** [comment]
@eefahy @jcoyne @cmh2166 

Following up on the above discussion, and seeing what seems to be accepted practice around this is to setup a testing initializer to capture flags. Review:

https://github.com/sul-dlss-labs/taco/blob/d4e2c596c967318c46ce6be97e3224cf426e40d1/test/initialize.go

and then it's included in each test:
https://github.com/sul-dlss-labs/taco/blob/d4e2c596c967318c46ce6be97e3224cf426e40d1/handlers/deposit_resource_test.go#L28

this may not be the best path, but is an option to allow us to define flags one place and not in each test file. Note, this branch isn't PR ready, but I'm happy to clean it up if we agree that this moves along all concerns.

**Comment by cmh2166** [comment]
@aaron-collier documented this in notes (in running notes, to be migrated to wiki).
