### ISSUE TITLE
Set currentVersion = true when a resource is created

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#290]
When a resource is initially created, the currentVersion needs to be set to `true`

**Comment by jcoyne** [comment]
@cmh2166 Presently our examples show that `"currentVersion": true` is being passed in.  Should we validate that the user has passed this in, or should we automatically set it?  If the latter, should I remove `"currentVersion: true"` from the examples?

**Comment by jcoyne** [comment]
Woah, this is odd. I see: `  "not": {"required": ["currentVersion", "id", "version"]},` in the maps too... so apparently `currentVersion` is not supposed to be present in the examples.

**Comment by cmh2166** [comment]
`currentVersion` is only set by the system and should not be provided by a user in a deposit payload.
