### ISSUE TITLE
Refactor retrieve resource to use map[string]interface{}

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#311]
Currently the retrieve resource builds a static struct, this should be updated to use the new pattern of `map[string]interface{}`

**Comment by cmh2166** [comment]
See if open PR #294 use of `dataUtils.Resource` covers this adequately.

**Comment by aaron-collier** [comment]
Confirmed #294 will closes this: https://github.com/sul-dlss-labs/taco/blob/0abbe85a0c24dd8bd3a5f5527f9e372128bea3ec/db/database.go#L46
