### ISSUE TITLE
UpdateResource validation - json schema

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#315]
**Validation Checks: Based on Resourcetype value**
- [ ] Input: NewResource (map[string]interface{}) & Resourcetype (string)
- [ ] Encode / Marshal NewResource (map[string]interface{}) to a JSON String
- [ ] Run JSON Schema Validation on the NewResource JSON string against its maps/[ResourceType].json
- [ ] If invalid, return data error to API caller (e.g. “Missing %v”, field)
- [ ] If valid, proceed to type-dependent validation checks

**Reference**
https://github.com/sul-dlss-labs/taco/wiki/TACO-Internal-Processing-Steps#update-resource

**Comment by jcoyne** [comment]
Is this done already?
