### ISSUE TITLE
UpdateResource - Collection & Object Validation

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#316]
if Resourcetype is Collection or Object:
- [ ] Check NewResource (map[string]interface{}) for a new or changed Identification.SourceId (string: map > string: string, will require casting)
- [ ] If NewResource.Identification.SourceId exists and is changed, retrieve & save to sourceId (string):
- [ ] Call to Dynamo’s SourceId Secondary Index to check that sourceId value does not already exist (except for OldRecord)
- [ ] If it already exists, return error to API caller (i.e. “Item is not unique; source ID already exists.”)
- [ ] If it does not, proceed
- [ ] If Identification.SourceId is not in NewResource or has not changed from ExistingResource, proceed

**Reference**
https://github.com/sul-dlss-labs/taco/wiki/TACO-Internal-Processing-Steps#update-resource

**Comment by jcoyne** [comment]
SourceID stuff is in #201
