### ISSUE TITLE
UpdateResource - Collection specific validation

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#317]
**When Resourcetype == Collection**
- [ ] Check if NewResource for a Collection has new or changed Structural.HasMember (array of string, druid + version)
- [ ] If so, check that all members are either type Collection or type Object
- [ ] If not (or it hasn't changed from ExistingResource), proceed

**Reference**
https://github.com/sul-dlss-labs/taco/wiki/TACO-Internal-Processing-Steps#update-resource

**Comment by jcoyne** [comment]
Done already?
