### ISSUE TITLE
UpdateResource - Object specific validation

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#318]
**When Resourcetype == Object**
- [ ] Check if Resource for a Object has new or changed Structural.HasMember (array of string, druid + version)
- [ ] If so, check that all members have @type == Object URI
- [ ] If not (or it hasn't changed from ExistingResource), proceed
- [ ] Check if Resource for a Object has new or changed Structural.Contains (array of string, UUID + version)
  - [ ] If so, check that all contained resources have @type == Fileset URI
  - [ ] If not (or it hasn't changed from ExistingResource), proceed

**Reference**
https://github.com/sul-dlss-labs/taco/wiki/TACO-Internal-Processing-Steps#update-resource

**Comment by jcoyne** [comment]
Done already?
