### ISSUE TITLE
UpdateResource - Fileset specific validation

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#319]
**When Resourcetype == Fileset**
- [ ] Check if Resource for a Fileset has new or changed Structural.ContainedBy (array of string, druid + version)
- [ ] If so, check that all parents (ContainedBys) ave @type == Object URI
- [ ] If not, return structural data error (e.g. "You are creating a Fileset without a representative Object")
- [ ] If it hasn't changed from ExistingResource, proceed

**Reference**
https://github.com/sul-dlss-labs/taco/wiki/TACO-Internal-Processing-Steps#update-resource

**Comment by jcoyne** [comment]
Done already?
