### ISSUE TITLE
UpdateResource - File specific validation

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#320]
**When Resourcetype == File**
- [ ] Check if Resource for a File has new or changed Structural.ContainedBy (array of string, UUID + version)
- [ ] If so, check that all parents (ContainedBys) have @type == Fileset URI
- [ ] If not, return structural data error (e.g. "You are creating a File without a container Fileset")
- [ ] If it hasn't changed from ExistingResource, proceed

**Reference**
https://github.com/sul-dlss-labs/taco/wiki/TACO-Internal-Processing-Steps#update-resource

**Comment by jcoyne** [comment]
Done already?
