### ISSUE TITLE
Deposit Resource - Data Mapping

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#341]
**Deposit Data Mapping**

 - [ ] Add Version information
   - [ ] On Resource, assert version (top level field) == 1 (integer). #246, #337
   - [ ] On Resource, assert currentVersion (top level) == True (boolean). #290
   - [ ] Add System Metadata
     - [ ] On Resource, assert depositor (top level field, Agent object) using Agent value (open policy question here).

**Comment by jcoyne** [comment]
This is a duplicate of issues already covered in #300
