### ISSUE TITLE
Inconsistence CircleCI biulds

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#344]
@eefahy something to look into, I tend to see a lot of initial (and sometimes repeated) build failures that eventually pass with a rerun. I'm assuming this is maybe a timing issue with getting localstack running as the errors are 500 responses from the services. Should we extend the pause time there again or is there something else that may need some attention?

**Comment by jcoyne** [comment]
I haven't seen this.  Odd.

**Comment by aaron-collier** [comment]
Closing as I haven't seen this again for a while and believe it was likely a timing issue during the builds. If it pops back up, we can re-open...
