### ISSUE TITLE
Depositor in TACO

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#361]
Depositor in TACO should be taken from a metadata field (i.e. json payload) and take the form of SunetID with domain (i.e. `cmharlow@standford.edu`, note, this is not the same as our email address). Derived from https://github.com/sul-dlss/sdr3-planning/issues/27

**Comment by jcoyne** [comment]
@cmh2166  should this replace the header auth? Should we retain the header auth to determine which client service is connecting?

**Comment by cmh2166** [comment]
This has been discussed and will be documented in the wiki. Closing this ticket with the merging of #81 however.
