### ISSUE TITLE
update MAPs to have depositor as field

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#363]
Derived from https://github.com/sul-dlss/sdr3-planning/issues/27

**Comment by jcoyne** [comment]
We already have this, right?
https://github.com/sul-dlss-labs/taco/blob/master/maps/DepositDRO.json#L42
https://github.com/sul-dlss-labs/taco/blob/master/maps/DepositFile.json#L24
https://github.com/sul-dlss-labs/taco/blob/master/maps/DepositCollection.json#L32
https://github.com/sul-dlss-labs/taco/blob/master/maps/DepositFileset.json#L24
https://github.com/sul-dlss-labs/taco/blob/master/maps/DRO.json#L41
https://github.com/sul-dlss-labs/taco/blob/master/maps/File.json#L23
https://github.com/sul-dlss-labs/taco/blob/master/maps/Collection.json#L31
https://github.com/sul-dlss-labs/taco/blob/master/maps/Fileset.json#L23

Can this be closed?

**Comment by cmh2166** [comment]
not yet, it also changes from where we pull the agent.

**Comment by jcoyne** [comment]
I'm confused.  Can we rewrite this ticket so that it is clear to everyone what is required?
