### ISSUE TITLE
When uploading a file, associate it with a Fileset

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#376]
See https://github.com/sul-dlss-labs/taco/pull/269/files#r179330969

We talked in standup 4/5/18 about using the `POST /resource/{fileset_id}/files` route rather than `/files` with a header to convey this information.

**Comment by cmh2166** [comment]
I could see either option being a good approach and await any pros / cons from your point of view. The only tricky part *could* be versions of Filesets.
