### ISSUE TITLE
Do we need to allow DepositFile.json as one of the DepositResource schemas?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#377]
It seems like we can get by with just creating the file using `handlers/deposit_file.go`, which will attach a File resource to the provided Fileset.

**Comment by cmh2166** [comment]
Yes, we do.

**Comment by cmh2166** [comment]
This is part of not have any resource type's data shape specified / buried in the go code but specified in a consistent MAPs doc.

**Comment by jcoyne** [comment]
My concern here is that we've made it possible for clients to create File objects and they can't get any file in storage attached to them.  Is that right?
