### ISSUE TITLE
Have Deposit File write valid File metadata

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#379]

**Comment by jcoyne** [comment]
By this we mean, run the JSON through the schema validation prior to persisting into dynamodb?

**Comment by cmh2166** [comment]
Well, and first actually capturing all the fields we know are required for a file.

**Comment by cmh2166** [comment]
The latest PR stores invalid files now.

**Comment by jcoyne** [comment]
@cmh2166 do we have defaults defined for the required fields? The ones that aren't immediately obvious to me are:

```
access.access
access.download
administrative.sdrPreserve
```

May I suggest we copy these values from the containing fileset upon deposit?

**Comment by jcoyne** [comment]
After #396 goes in, we would still need to set a "label" for it to be valid.  What should we set that to?

**Comment by cmh2166** [comment]
label == filename at the moment / for this work cycle.
