### ISSUE TITLE
Go configuration management instead of env variables?

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#38]

**Comment by aaron-collier** [comment]
See the viper stuff in #40

**Comment by cmh2166** [comment]
Yes, but do we need the viper stuff, or are we missing an opportunity to simplify? @aaron-collier

**Comment by aaron-collier** [comment]
I think we might be, yes. I'm happy to work on this.

**Comment by aaron-collier** [comment]
We could do something like this: http://goinbigdata.com/persisting-application-configuration-in-golang/ to help limit our external dependencies.

**Comment by jcoyne** [comment]
Why do we want to limit dependencies? I’d rather not maintain code that we don’t have to.

**Comment by aaron-collier** [comment]
#119 will close this.
