### ISSUE TITLE
Any non-technical requirement for ur-agreement?

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#405]
Do we have any reason beyond recursion of data model for the sake of technological concerns (i.e Agreements are Objects too so need an Agreement like all Objects) to have an Ur-Agreement?

**Comment by hannahfrost** [comment]
No, there is no reason as far as I know.

**Comment by blalbrit** [comment]
I think we were limited by data model previously - *all* objects had to have an APO, therefore APOs had to have an APO, etc. (recursion as you say). The only caution about relaxing that is that I've been tracking new ETDs that were submitted to SDR without an APO, so we just need to be rigorous in our screening of such objects. In the current model - "items" must require an APO, "collections" should require an APO, but presumably workflows, APOs and other administrative objects probably don't.

However that translates to the new model. :-)
