### ISSUE TITLE
isDescribedBy is not getting set on deposit

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#430]
Related to #408, the `administrative/isDescribedBy` metadata field is not set and thus we're unable to round trip data for update.

**Comment by cmh2166** [comment]
for sure. this is a victim of the processing changes + refritos redo. it'll probably not be addressed in the remaining time of this work cycle :-|

**Comment by aaron-collier** [comment]
Cool, glad to just capture it. :-)

**Comment by jcoyne** [comment]
@aaron-collier can you explain the steps needed to duplicate this? When I added `administrative.isDescribedBy` to `examples/request.json` and then run the deposit with that file, and then retrieve it, I get the `administrative.isDescribedBy` value that I provided:

```
{
	"$comment": "This is a fixture used for testing. It was derived from create-bs646cd8717.json",
	"@context": "http://sdr.sul.stanford.edu/contexts/taco-base.jsonld",
	"@type": "http://sdr.sul.stanford.edu/models/sdr3-collection.jsonld",
	"access": {
		"access": "world",
		"copyright": "This work is copyrighted by the creator.",
		"download": "world",
		"reuseAndReproductionStatement": "Property rights reside with the repository. Literary rights reside with the creators of the documents or their heirs. To obtain permission to publish or reproduce, please contact the Special Collections Public Services Librarian at speccollref@stanford.edu."
	},
	"administrative": {
		"deleted": false,
		"isDescribedBy": "https://purl.stanford.edu/bq582kh2487.xml",
		"remediatedBy": [{
			"name": "Laura Wilsey",
			"sunetID": "lauraw15"
		}],
		"sdrPreserve": true
	},
	"citation": "Leon Kolb Collection of Portraits. https://purl.stanford.edu/bs646cd8717",
	"depositor": {
		"name": "DOR",
		"sunetID": "DOR"
	},
	"externalIdentifier": "08045fa1-13be-4904-bdb3-55e04182cf37",
	"identification": {
		"catkey": "4084372",
		"sourceId": "bib4084372"
	},
	"label": "Leon Kolb Collection of Portraits",
	"structural": {
		"hasAgreement": "druid:dd327qr3670",
		"hasMember": null,
		"hasMemberOrders": null,
		"isTargetOf": null
	},
	"tacoIdentifier": "f5de1ecb-6f80-4d84-aaeb-5d1a0bf2df2b",
	"version": 1
}
```

**Comment by cmh2166** [comment]
This is a different round trip- ie PURL to TACO MAP json.

This is already captured and documented with metadata and with refritos work, so closing to avoid further confusion.

**Comment by cmh2166** [comment]
(Unless @aaron-collier you had a different reason for opening)

**Comment by aaron-collier** [comment]
WFM @cmh2166 , just capturing what I saw, and should have been more clear. Since this is a field not allowed on deposit, but required on update, just need to be aware.
