### ISSUE TITLE
Write DeleteResource handler (stub)

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#48]

**Comment by cmh2166** [comment]
blocked by #150

**Comment by aaron-collier** [comment]
No longer blocked.

"Delete" (as understood at the higher level administration level marks a record and provides a gravestone message) - Will:
- Calls `PATCH /resource/{id}`
- Payload: delete: true, gravestronemsg: string, access: false, publish: false
- Permissions updated - To Be Defined
- Message to processing

TACO Delete (aka Purge)
- Calls: `DELETE /resource/{id}`
- Payload: empty
- Deletes record from Dynamo
- Deletes binary from S3 (when relevant)
- Messages processing (to remove structural pointers, access, pres core - OUTSIDE OF TACO)

**Comment by jcoyne** [comment]
Regarding `access: false`. Currently access is a string that is constrained to be an enumeration.  Should we change that constraint, or should we change this requirement to be something like `access: "dark"`?
