### ISSUE TITLE
Do we need a RetrieveFile and/or DeleteFile Handler

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#50]
Tied to whether or not this API gates those functions directly on the binary (or we just pass File metadata with location back and the location [S3] is how one does those functions)

**Comment by jcoyne** [comment]
I think we *should* build a RetrieveFile function as it seems like it will become necessary when we have access controls, and this would make the prototype show better because otherwise the client would have to have the same credentials as taco in order to retrieve the files directly from s3.

**Comment by cmh2166** [comment]
I think we all kinda agreed to this wrt having permissions only managed via calls to permissions services instead of also doing S3 permission checks. See  opened ticket. Will add backlog ticket for DeleteFile Handler then close this unless @eefahy or @aaron-collier have any concerns.

**Comment by eefahy** [comment]
good here. Thanks for asking.

**Comment by aaron-collier** [comment]
Agreed. It the more specific tickets close this one.
