### ISSUE TITLE
Get shared protocol for local dev with AWS stubs

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#65]
This removes AWS setup blocker from code work, at least for the time being.

**Comment by jcoyne** [comment]
The readme already describes how to use localstack https://github.com/sul-dlss-labs/taco#running-the-taco-binary  Is this sufficient?

**Comment by cmh2166** [comment]
I think so... @aaron-collier are you able to get the same setup from that? @eefahy is this good for your purposes, trying to keep devs separate from AWS setup for now?

**Comment by cmh2166** [comment]
Do we understand this now?

**Comment by aaron-collier** [comment]
@cmh2166 It's there but I don't think it's complete. I do think that section should be moved into the dev doc (coming), when that's complete, I'll close this.

**Comment by cmh2166** [comment]
@aaron-collier complete now?

**Comment by cmh2166** [comment]
Just closing, looks done per @jcoyne 's comment.
