### ISSUE TITLE
Coverage tool?

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#68]
Needed?

**Comment by jcoyne** [comment]
I say no. I think coverage is often a misleading metric about the quality of tests.  It's very easy to write a fully covered suite, but it doesn't mean the tests are any good.  PR reviewers should ensure that sufficient tests have been added to cover the likely scenarios.

**Comment by aaron-collier** [comment]
I wouldn't say outright no, maybe we back lot this for now. It's earl to require it, and as @jcoyne says, ensuring sufficient tests should answer it. But we may find it necessary eventually.

**Comment by cmh2166** [comment]
I leave it to others. @eefahy

**Comment by jcoyne** [comment]
In our meeting today the team decided that this is not needed at present.
