### ISSUE TITLE
Review testing for go-swagger generated code

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#69]
Complete enough to warrant our not testing generated code?

**Comment by jcoyne** [comment]
We have already had an incident where the build was green but the application was broken, so no, I don't think we're testing well enough. We need integration tests.

**Comment by cmh2166** [comment]
Agree. Will open a new ticket on Monday for this.

**Comment by jcoyne** [comment]
Will #85 resolve this?
