### ISSUE TITLE
add to README info on go, dep versions

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#73]
In the meeting on 1/29 we decided we would use 1.9/latest.  We should add this fact into the README.

**Comment by jcoyne** [comment]
I've been using go 1.9 locally, but I see that CircleCi is configured to use 1.8. Does anyone have a reason why we don't all want to start on the latest available version?

**Comment by cmh2166** [comment]
I don't know to be honest. @eefahy any reason what CircleCI is configured for 1.8? I've been using 1.9 locally as well, fwiw.

**Comment by cmh2166** [comment]
Is this not closed?
