### ISSUE TITLE
issue with dep and aws-sdk library

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#74]

**Comment by jcoyne** [comment]
Not certain what the problem is here. Seeing `github.com/aws/aws-sdk-go` in Gopkg.lock.

**Comment by cmh2166** [comment]
It's a compile issue.

**Comment by cmh2166** [comment]
with dep and this library, well known it appears from the gh issues (see issue of go get hiding this fat)

**Comment by jcoyne** [comment]
Can you give me more details when you see this again?  I'd like to know how I can duplicate it.

**Comment by cmh2166** [comment]
fixed via consistent dep practices across team + latest version usage.
