### ISSUE TITLE
update dependencies in dep, clean up go get usage that goes around this

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#75]

**Comment by jcoyne** [comment]
I don't understand what this means. Where are we using `go get`?  It looks like the CI build uses `dep ensure`

**Comment by cmh2166** [comment]
yes, we are using dep ensure. go get in some of the docs i think is hiding our misuse of go ensure.

**Comment by cmh2166** [comment]
Link to this for dep info would be good: https://gist.github.com/subfuzion/12342599e26f5094e4e2d08e9d4ad50d It basically comments on what we went through today and the practice we're evolving too (using taht toml file to guide the rest of the build)

**Comment by jcoyne** [comment]
Having problems with using `dep ensure -add pkg`

```$ dep ensure -add github.com/buger/jsonparser
Fetching sources...

Failed to add the dependencies:

  ✗ github.com/buger/jsonparser is already imported or required, so -add is only valid with a constraint

adding dependencies failed
```

jsonparser is not in the toml file, but it already is in the lock file.

**Comment by cmh2166** [comment]
related to #94
