### ISSUE TITLE
Should the server create the kinesis channel if it doesn't exist?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#78]
Or should we create the channel ahead of time?

**Comment by cmh2166** [comment]
Or do we need to know this now, as there may be processing code given our design between the API and Kinesis?

**Comment by jcoyne** [comment]
I think we should make something simple that works now until we determine how to incorporate airflow.

**Comment by cmh2166** [comment]
Is this done?

**Comment by cmh2166** [comment]
(I think we discussed it possibly earlier this week)

**Comment by jcoyne** [comment]
I think we said, no, the server should not create it.  It will just be part of the setup tasks.
