### ISSUE TITLE
Explore permissions using Swagger.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#79]
The generated code doesn’t give us much to validate on presently. Do we have to add something to the swagger.yaml?

See #81

**Comment by cmh2166** [comment]
Depends on what you mean by validate.

1. validate swagger? yes thats in the tool and docs.
2. validate a user? emphatically should not be in the API spec.

**Comment by aaron-collier** [comment]
Agree with @cmh2166 here, aside from validating the swagger, anything else is out of scope.

**Comment by jcoyne** [comment]
This is what I'm talking about: https://swagger.io/docs/specification/2-0/authentication/api-keys/

Otherwise, I'm not seeing how our handlers have a concept of who the interacting user is and thus we can't do authorization.
