### ISSUE TITLE
Swagger request for file deposit looks incorrect

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/taco#87]
It's showing the body to be JSON, but shouldn't it be the binary itself?

Shouldn't it accept a request such as:
```
curl -X POST -d @README.md http://localhost:8080/file
```

**Comment by cmh2166** [comment]
we haven't decided yet (until today) what this looked like, so part of docs / swagger update.

**Comment by jcoyne** [comment]
@cmh2166 are you saying that #135 addresses this? I think it still needs some work. See https://github.com/sul-dlss-labs/taco/pull/135#discussion_r164941256

**Comment by cmh2166** [comment]
You mean that work in progress PR that I am still working on? :-)

**Comment by cmh2166** [comment]
I think reading through swagger 2.0 spec recs for this, this should now be correct: https://github.com/sul-dlss-labs/taco/blob/swagger_updates/swagger.json#L131 

I am regenerating the API code now to test.
