### ISSUE TITLE
POs Review Env Question

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#9]
Should there be a -dev or -stage or other demo instance that is available to the product owner and other reviewers?

**Comment by aaron-collier** [comment]
Verify that prototype has single endpoint.

**Comment by hannahfrost** [comment]
@blalbrit @LynnMcRae  @vivnwong @tomcramer 

Can we agree that at the end of the present work cycle, the TACO prototype need only be available at one endpoint (no need for -dev, -stage, -prod) and there need not be specific guarantees on uptime availability (SLA level: low)?

**Comment by vivnwong** [comment]
For TACO, yes and yes.

I assume when we venture into the next WC and do more integrations with other services, we then need to reevaluate this question again.

Vivian

On Mar 1, 2018, at 3:47 PM, hannahfrost <notifications@github.com<mailto:notifications@github.com>> wrote:


@blalbrit<https://github.com/blalbrit> @LynnMcRae<https://github.com/lynnmcrae> @vivnwong<https://github.com/vivnwong> @tomcramer<https://github.com/tomcramer>

Can we agree that at the end of the present work cycle, the TACO prototype need only be available at one endpoint (no need for -dev, -stage, -prod) and there need not be specific guarantees on uptime availability (SLA level: low)?

**Comment by cmh2166** [comment]
Considering this close-able with the above captured in the ticket.
