### ISSUE TITLE
stub out services we aren't building now

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#90]
identifier service? permissions service? provenance service? downstream services?

**Comment by aaron-collier** [comment]
@aaron-collier will break this up into individual tickets.

**Comment by jcoyne** [comment]
Are we imagining these will be actual codebases/containers that we'll deploy?

**Comment by cmh2166** [comment]
keeping this out of high level given our previous discussion on what that is (milestones for vivian)

**Comment by cmh2166** [comment]
Breaking out now in prep for planning (don't see where @aaron-collier was able to get to it)
