### ISSUE TITLE
Walk through dep ensure as group

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#94]
- [ ] Pull new go project
- [ ] Run dep ensure
- [ ] Verify updates to lock file
- [ ] Agree on verification progress and README is updated.

**Comment by aaron-collier** [comment]
#73 and #75

**Comment by cmh2166** [comment]
Walking through this with a new project convinces me that we are misusing the toml file. I'd like to use it for handling how we share what then gets added to the lock file. It is more explicit then import guessing by the library, which seems better imho.

**Comment by aaron-collier** [comment]
Walked through various ways of initializing dependencies on a blank go project. I agree with @cmh2166 here, we initially had a dilution of dependencies from `import` calls as well as loaded via `go get [some dependency]`, the latter of which causes a discrepancy between the toml/lock and the vendor dir. We should stick to `import` calls in code and `dep ensure`, avoiding `go get` and the vendor dir.
